name: Django CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --no-root
      - name: Lint
        run: |
          poetry run flake8 src/ tests/ manage.py 
          poetry run isort .
      - name: Run Tests
        run: |
          poetry run pytest .
